import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import SectionHeader from "@/components/header";
import SecttionPortfolio from "@/components/portfolio";
import SectionAbout from "@/components/about";
import SectionTestimonials from "@/components/testimonials";
import SectionContact from "@/components/contact";
import SectionProduct from "@/components/product";

export default function Home() {
  return (
    <>
      <Head>
        <title>Figma Design 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SectionHeader />
        <SecttionPortfolio />
        {/* <SectionAbout />
        <SectionTestimonials />
        <SectionContact />
        <SectionProduct /> */}
      </main>
    </>
  );
}
